services:

  trainer:
    build: train_image
    depends_on:
      - mlflow_server
    env_file:
      - train_image/local.env
    environment:
      - MLFLOW_DATABASE_URI=${MLFLOW_DATABASE_URI}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    shm_size: 2gb
    volumes:
      - ${BASE_DIR}/configs:/app/configs
      - ${BASE_DIR}/visdrone:/app/visdrone
      - ${MLFLOW_BASE_DIR}:/app/mlruns
      - ${MLFLOW_DATA_DIR}:/data
      - ${MLFLOW_DATA_DIR}/default_models:/root/.cache/torch/hub/checkpoints

  mlflow_database:
    build: mlflow_database_image
    environment:
      - MLFLOW_DATABASE_PASSWORD=${MLFLOW_DATABASE_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - ${MLFLOW_DATABASE}:/var/lib/postgresql/data

  mlflow_server:
    build: mlflow_server_image
    depends_on:
      - mlflow_database
    environment:
      - MLFLOW_DATABASE_URI=${MLFLOW_DATABASE_URI}
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - ${MLFLOW_BASE_DIR}:/app/mlruns