#!/bin/bash

psql << EOF
CREATE DATABASE mlflow;
CREATE USER mlflow WITH ENCRYPTED PASSWORD $MLFLOW_DATABASE_PASSWORD;
GRANT ALL PRIVILEGES ON DATABASE mlflow TO mlflow;
EOF

psql << EOF
CREATE DATABASE airflow;
CREATE USER airflow WITH ENCRYPTED PASSWORD $AIRFLOW_DATABASE_PASSWORD;
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
EOF